### PR TITLE
Code blocks with specified language

### PR DESCRIPTION
**Pull request by andreskrey**
Hi.

This fixes issue #70 

It's a rather large change. This mainly changes the way the system generates the code blocks. Previously, the system preferred the four spaces tag to denote a code block. This PR changes that to three backticks. The reason behind this is to allow the possibility to add a language descriptor to the code tag.

It can detect the code language and add it to the tag, or just leave it as a non-specific code fence.

I also modified the tests to reflect this change.

For example, this html code...

`<pre><code>&lt;p&gt;Some sample HTML&lt;/p&gt;</code></pre>`

...will generate this markdown:

    ```
    <p>Some sample HTML</p>
    ```

This was made possible by adding a new converter that handles the Code tag specifically. The Preformatted converter is pretty much untouched, although it doesn't add 4 spaces anymore. I found that the commonmark specs do not mention what should happen to pre tags that aren't wrapping code tags, so I left the functionality as it was, which right now consists in normalizing EOLs.

If you think this is not the correct approach, let me know and I'll do the appropriate changes.

### CODE REVIEW

**Comment by colinodell** [comment]
> I found that the commonmark specs do not mention what should happen to pre tags that aren't wrapping code tags, so I left the functionality as it was, which right now consists in normalizing EOLs.

Yeah, that's a tricky one.

In my opinion, there are two scenarios when this might happen:

1. The inner text is code; the website should've used `<code>` tags but didn't
2. The inner text is non-code where whitespace is important (like poetry)

In both cases, whitespace should be preserved and a monospaced font should be used by default.  Users are explicitly labeling content as being pre-formatted, so we should try to maintain that when making the conversion.  To do so, we basically have two choices:

1. Convert to code blocks/inlines
  - This is the current functionality
2. Preserve the `<pre>` tags
  - Doable, but may cause issues if the Markdown renderer doesn't allow raw HTML

For the best compatibility, I think we should go with option 1 - convert `<pre>` content to code blocks (three backticks) or inlines (one backtick).

Would you mind modifying your changes to support this (and revert the corresponding test changes too)?

Otherwise I'm in favor of making this change :)

**Comment by andreskrey** [comment]
Agree!

I'll do the changes this week. I'm assuming we'll only honor the language tag only if it is inside the code tag, right?

For example:

`<pre><code class="language-php">&lt;?php //Some php code ?&gt:</code></pre>`

Would generate this result:

```
    `php <?php //Some php code ?>`
```

But this code:

`<pre class="language-php">&lt;?php //class on the pre tag, incorrect usage ?&gt:</pre>`

Will generate this result:


```
    `<?php //class on the pre tag, incorrect usage ?>`
```

**Comment by colinodell** [comment]
> I'll do the changes this week.

Awesome, thank you!

> I'm assuming we'll only honor the language tag only if it is inside the code tag, right?

Yeah that makes sense to me :)

**Comment by andreskrey** [comment]
Done.

Since the code tag will always be nested inside the pre tag, I decided to keep the CodeConverter and detect the backticks on the PreConverter. This means that when the PreConverter fires, it will check the boundaries of the string, and if both ends have a backtick, it will assume it was a `<pre><code>` code style and return the string as it was converted

If no backticks are found, it will add them depending if the string has one or more lines, using one or three respectively.

This approach has the drawback that the backtick adding function is exactly the same in the Code and Pre converters, which isn't very DRY. I considered parsing the code tag inside the pre tag, but this would be against the Single Responsibility principle, because the Pre converter will be in charge of two different functionalities.

What do you think?

**Comment by andreskrey** [comment]
@colinodell bump

**Comment by colinodell** [comment]
Sorry for the delay.

> This approach has the drawback that the backtick adding function is exactly the same in the Code and Pre converters, which isn't very DRY.

I'm reminded of this quote:

> duplication is far cheaper than the wrong abstraction

So I don't particularly mind having a little duplicate code.  We can always refactor it later :)

Thanks for implementing these changes!

**Pull request merged**
