### PR TITLE
Add more export-ignore to slim down composer package.

### PR DESCRIPTION
**Pull request by jdufresne**

### CODE REVIEW

**Comment by colinodell** [comment]
I'd like to keep the `README`, and probably `demo` too. If you could remove
those lines I'll go ahead and accept this.

Thanks!

**Comment by jdufresne** [comment]
> I'd like to keep the `README`, and probably `demo` too. If you could remove those lines I'll go ahead and accept this.

Done. 

However, I ask that you reconsider the `demo` directory.

Keep in mind that many people use composer to download dependencies for production sites. Downloading third party documentation and examples is time consuming and goes to waste on these sites. The demo is still available to those who want it, but not forced on people during production deployment. As more and more 3rd party packages include examples, documentation and tests, the extra time spent during deployment of these sites really adds up.

**Comment by colinodell** [comment]
You make some really good points.  I definitely want to keep the `README`, as it's a single file with everything you'd need to know.

The more I think about it, the more I feel we can probably maybe remove the `demo` altogether since only a handful of users would find it useful, compared the `README` which is useful for everyone.  Would you like to submit a PR for it's deletion?  We'll keep it open for a few days in case there are objections and then hopefully accept it :)

**Comment by jdufresne** [comment]
> Would you like to submit a PR for it's deletion? We'll keep it open for a few days in case there are objections and then hopefully accept it :)

Will do. Thanks.

**Pull request merged**
